.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH JACKFREQD 1 "December  12, 2010"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
jackfreqd \- control CPU speed according to DSP load
.SH SYNOPSIS
.B jackfreqd
.RI [ options ] 
.SH DESCRIPTION
This simple client controls CPU speed and voltage using the sysfs interface
to the CPUFreq driver in v2.6 Linux kernels. It does not depend on APM or
ACPI, and it doesn't try to do anything other than control the CPU via
the userspace governor and sysfs.

jackfreqd is a variant of powernowd tailored for pro-audio work.

The CPU-frequency is scaled depending on DSP and system-load. 
On multi-threaded system the system-load may still be too low for a
default governor to kick in while DSP load is already at the limit.

.SH OPTIONS
.TP
.B \-h
Prints a help message.
.TP
.B \-d
Detach from terminal and run in background
.TP
.B \-v
Increase output verbosity, can be used more than once.
.TP
.B \-q
Quiet mode, only emergency output.
.TP
.B \-P
Make frequency scaling decision based on both DSP and CPU load:
use higher value of both.
.TP
.B \-n
Include nice'd processes in calculations (only with \-P).
.TP
.B \-c
Specify number of threads per power-managed core.
.TP
.B \-s
Frequency step in kHz (default = 100000)
.TP
.B \-p
Polling frequency in msecs (default = 1000)
.TP
.B \-u
DSP usage upper limit percentage [0 .. 100, default 50]
.TP
.B \-l
CPU usage lower limit percentage [0 .. 100, default 10]
.TP
.B \-U
CPU usage upper limit percentage [0 .. 100, default 80]
.TP
.B \-L
CPU usage lower limit percentage [0 .. 100, default 20]
.TP
.B \-w
wait for and re-connect to jackd. Should be combined with \-P.
Otherwise if no jack process is available CPU will stay in
low power-mode independent of CPU activity.
.TP
.B \-j
user-name or UID of jackd process (default: autodetect)
.TP
.B \-J
group-name or GID of jackd process (default: autodetect)

.SH AUTHOR
jackfreqd was created by Robin Gareus <robin@gareus.org>. 
It is heavily based on the powernowd program by John Clemens <clemej@alum.rpi.edu>
